version: '3'

#volumes:
#    home_psweet:

services:

  psweet-service:
    build:
        args: # These don't work
        - CPUS=1
        - BUILD_TYPE=Release
        context: .
        dockerfile: Dockerfile
    image: stevenrbrandt/psweet
    hostname: psweet-host
    container_name: psweet
    entrypoint: sleep infinity
